// console 05 §6 (D50): the command sheet crosses from the CLI as data. The
// CLI build emits `engine/cli/dist/sheet.json`; this writes it into
// `content/commands.generated.ts` so the browser bundle never imports the
// CLI package. `test/unit/sheet.test.ts` fails when the two differ.
import { readFileSync, writeFileSync } from "node:fs";

export const SOURCE = new URL("../../engine/cli/dist/sheet.json", import.meta.url);
export const TARGET = new URL("../content/commands.generated.ts", import.meta.url);

export function render(json) {
  const { groups } = JSON.parse(json);
  return (
    "// Generated by `npm run sheet` from engine/cli/dist/sheet.json — do not edit (console 05 §6, D50).\n" +
    "// Source of truth: engine/cli/src/commands/sheet.ts.\n\n" +
    "export interface CommandRow {\n  what: string;\n  run: string;\n  note?: string;\n}\n\n" +
    "export interface CommandGroup {\n  group: string;\n  rows: CommandRow[];\n}\n\n" +
    `export const COMMAND_SHEET: CommandGroup[] = ${JSON.stringify(groups, null, 2)};\n`
  );
}

if (process.argv[1] === new URL(import.meta.url).pathname) {
  writeFileSync(TARGET, render(readFileSync(SOURCE, "utf8")));
}
