import { createHash, timingSafeEqual } from "node:crypto";
import { chmodSync, rmSync } from "node:fs";
import { createServer, type IncomingMessage } from "node:http";
import type { AddressInfo, Socket } from "node:net";
import type { Blocker, EndpointTally, MintedCredential, SpawnPlan } from "@harness/compose/contracts";
import { inject } from "./inject.js";
import { type EndpointLog, openLog } from "./log.js";
import { tunnel } from "./tunnel.js";

/** 05 §4. Private to this module: nothing outside 08 constructs one. */
export interface ProxyOptions {
	plan: Pick<SpawnPlan, "hosts" | "deny" | "reach" | "connectors">;
	credentials: MintedCredential[];
	secret: string; // 32 random bytes, base64url; generated by 08
	sessionDir: string;
	// 08 pre-allocates the loopback port so `render` and the plan can name the
	// URL before the fence binds; `port` is that number on both transports.
	listen: { kind: "tcp"; port?: number } | { kind: "unix"; path: string; port: number }; // §4.1
	notify: (message: string) => void; // one line to the person; 08 prints it
}

export interface Proxy {
	readonly url: string; // http://:<secret>@127.0.0.1:<port>
	retire(alias: string): void; // §7.2
	close(): Promise<void>; // §7.3
	tally(): EndpointTally[];
}

/** §7's table: what the proxy holds per alias. Never logged, never rendered. */
export interface Credential {
	value: string;
	kind: MintedCredential["kind"];
	expiresAt: string | null;
	retired: boolean;
}

/** The state both modes share — one object, created once, passed (10 rule 11). */
export interface Ctx {
	plan: ProxyOptions["plan"];
	credentials: Map<string, Credential>;
	log: EndpointLog;
	/** §9: the person hears each sentence once per session. */
	notify: (message: string) => void;
	/** §4.3, `proxy.auth.bad_secret` when it fails. `injectMode` adds the two
	    carriers only inject accepts. */
	authenticate: (req: IncomingMessage, injectMode: boolean) => boolean;
	/** `proxy.closed`: after §7.3 every request in either mode is refused. */
	isClosed: () => boolean;
	/** Established tunnels, destroyed by `close()` (§7.3). */
	tunnels: Set<Socket>;
}

/**
 * 05 — the fence. One listener, two modes that never mix (P2), one log.
 */
export async function startProxy(opts: ProxyOptions): Promise<Proxy> {
	const credentials = new Map<string, Credential>();
	for (const minted of opts.credentials) {
		credentials.set(minted.alias, { value: minted.value, kind: minted.kind, expiresAt: minted.expiresAt, retired: false });
	}
	for (const alias of Object.keys(opts.plan.connectors)) {
		// §7: a connector with no credential is a bug in 03, and a proxy must
		// never start with a hole (I5).
		if (!credentials.has(alias)) {
			const blocker: Blocker = {
				code: "proxy.missing_credential",
				message: `The broker did not supply a credential for "${alias}".`,
				remedy: "Run harness preflight credentials; the slot names the group that should cover it.",
			};
			throw blocker;
		}
	}
	const log = openLog(`${opts.sessionDir}/endpoints.jsonl`);
	const expected = createHash("sha256").update(opts.secret).digest();
	const said = new Set<string>();
	const tunnels = new Set<Socket>();
	let closed = false;
	const ctx: Ctx = {
		plan: opts.plan,
		credentials,
		log,
		notify(message) {
			if (said.has(message)) return;
			said.add(message);
			opts.notify(message);
		},
		authenticate: (req, injectMode) => presented(req, injectMode).some((value) => sameSecret(value, expected)),
		isClosed: () => closed,
		tunnels,
	};

	const server = createServer((req, res) => void inject(req, res, ctx));
	// The `connect` event types its stream as a Duplex; it is always the
	// net.Socket the tunnel splices.
	server.on("connect", (req, socket, head) => void tunnel(req, socket as Socket, head, ctx));
	await new Promise<void>((resolve) => {
		if (opts.listen.kind === "unix") server.listen(opts.listen.path, resolve);
		else server.listen(opts.listen.port ?? 0, "127.0.0.1", resolve);
	});
	// §4.1: the socket is a file, so it is narrowed to this user the moment it
	// exists; the secret then narrows it to this session (G6).
	if (opts.listen.kind === "unix") chmodSync(opts.listen.path, 0o600);
	const port = opts.listen.kind === "unix" ? opts.listen.port : (server.address() as AddressInfo).port;

	return {
		url: `http://harness:${opts.secret}@127.0.0.1:${port}`,
		retire(alias) {
			// §7.2 (D69): a rotated key refuses this alias from the next request
			// on; the session continues and an in-flight stream is not cut.
			const credential = credentials.get(alias);
			if (credential) credential.retired = true;
		},
		async close() {
			if (closed) return; // close_twice_is_harmless (10 rule 19)
			closed = true;
			for (const socket of tunnels) socket.destroy();
			tunnels.clear();
			await new Promise<void>((resolve) => {
				server.close(() => resolve());
				server.closeAllConnections();
			});
			if (opts.listen.kind === "unix") rmSync(opts.listen.path, { force: true });
			log.close();
			// §7.3: best effort in a managed runtime; the habit costs nothing.
			for (const credential of credentials.values()) credential.value = "\u0000".repeat(credential.value.length);
			credentials.clear();
		},
		tally: () => log.tally(),
	};
}

/** §4.3's table, in order. All three are stripped before anything is forwarded. */
function presented(req: IncomingMessage, injectMode: boolean): string[] {
	const values: string[] = [];
	const basic = req.headers["proxy-authorization"];
	if (typeof basic === "string" && basic.startsWith("Basic ")) {
		const decoded = Buffer.from(basic.slice(6), "base64").toString("utf8");
		values.push(decoded.slice(decoded.indexOf(":") + 1));
	}
	if (!injectMode) return values;
	const bearer = req.headers.authorization;
	if (typeof bearer === "string" && bearer.startsWith("Bearer ")) values.push(bearer.slice(7));
	const key = req.headers["x-api-key"];
	if (typeof key === "string") values.push(key); // D70: Anthropic-shaped clients
	return values;
}

/** Constant-time: SHA-256 both sides, then `timingSafeEqual` (§4.3). */
function sameSecret(value: string, expected: Buffer): boolean {
	return timingSafeEqual(createHash("sha256").update(value).digest(), expected);
}
