// Generated by `npm run sheet` from engine/cli/dist/sheet.json — do not edit (console 05 §6, D50).
// Source of truth: engine/cli/src/commands/sheet.ts.

export interface CommandRow {
  what: string;
  run: string;
  note?: string;
}

export interface CommandGroup {
  group: string;
  rows: CommandRow[];
}

export const COMMAND_SHEET: CommandGroup[] = [
  {
    "group": "Pick something up",
    "rows": [
      {
        "what": "Work on your version of a harness",
        "run": "harness switch campaign-drafts"
      },
      {
        "what": "Run the session on the team's version",
        "run": "harness switch campaign-drafts --team",
        "note": "anything you change still lands on your version"
      },
      {
        "what": "Start a session",
        "run": "harness run pi",
        "note": "the provider is the word; the harness is what you switched to"
      },
      {
        "what": "Start one from a card in the console",
        "run": "harness open harness://run?harness=<id>&provider=pi",
        "note": "what the card's button does: asks for a folder, then opens a terminal in it"
      },
      {
        "what": "Make a new harness",
        "run": "harness new \"Weekly newsletter\"",
        "note": "starts empty; hands you harness switch"
      },
      {
        "what": "Make one from a copy",
        "run": "harness new \"Weekly newsletter\" --from campaign-drafts"
      },
      {
        "what": "Bring in an existing provider setup",
        "run": "harness import claude",
        "note": "prints what was carried, partial or dropped; nothing is pushed until you review it"
      }
    ]
  },
  {
    "group": "See what is going on",
    "rows": [
      {
        "what": "What you have changed, and what is in conflict",
        "run": "harness status",
        "note": "no network"
      },
      {
        "what": "The difference on one file",
        "run": "harness diff skill/campaign-brief",
        "note": "--team compares to the team's copy; --git prints the hunk"
      },
      {
        "what": "History of your version",
        "run": "harness log",
        "note": "--team for the team's"
      },
      {
        "what": "What will and will not resolve before you start",
        "run": "harness preflight",
        "note": "--<harness> overrides the selection"
      },
      {
        "what": "Bring the work tree up to date",
        "run": "harness pull",
        "note": "never overwrites a change of yours"
      },
      {
        "what": "Who you are and what you have",
        "run": "harness whoami"
      }
    ]
  },
  {
    "group": "Change something",
    "rows": [
      {
        "what": "Keep your version — nobody reviews it",
        "run": "harness push tool/crm-sync --message \"Retry flaky list calls\"",
        "note": "lands in the harness you switched to; --harness names another"
      },
      {
        "what": "Offer it to the team",
        "run": "harness offer tool/crm-sync --message \"Retry flaky list calls\"",
        "note": "opens a request an admin sees"
      },
      {
        "what": "Withdraw an offer",
        "run": "harness withdraw <request-id>"
      },
      {
        "what": "Take something out of your harness",
        "run": "harness remove tool/crm-sync",
        "note": "your copy leaves your branch; the team's copy stays theirs"
      },
      {
        "what": "Take the team's version of one file",
        "run": "harness reset tool/crm-sync",
        "note": "asks first unless --yes"
      },
      {
        "what": "Take the team's for everything",
        "run": "harness reset --all"
      },
      {
        "what": "Adopt something you made by hand",
        "run": "harness adopt ./my-tool",
        "note": "mints its id"
      }
    ]
  },
  {
    "group": "Set up",
    "rows": [
      {
        "what": "See what is left to set up",
        "run": "harness setup",
        "note": "each missing step prints the command that closes it; also registers `harness://` links"
      },
      {
        "what": "Stop `harness://` links opening on this machine",
        "run": "harness setup --unregister"
      },
      {
        "what": "See every runtime and its approval",
        "run": "harness providers"
      },
      {
        "what": "Turn a runtime on",
        "run": "harness providers approve pi",
        "note": "org admin; --teams narrows who may run it"
      },
      {
        "what": "Turn a runtime off",
        "run": "harness providers decline claude --reason \"…\""
      },
      {
        "what": "Connect a model key",
        "run": "harness keys add openrouter",
        "note": "prompts for the key; sets it as the organisation's default"
      },
      {
        "what": "Make a harness for a team",
        "run": "harness new \"Weekly newsletter\" --team marketing",
        "note": "--org for every team; without a flag it is yours alone"
      }
    ]
  },
  {
    "group": "Sign in",
    "rows": [
      {
        "what": "Sign in to the platform",
        "run": "harness login"
      },
      {
        "what": "Sign in to a runtime with your own account",
        "run": "harness auth claude",
        "note": "outside the sandbox; native mode"
      },
      {
        "what": "Sign in to Claude or ChatGPT inside Pi",
        "run": "harness auth pi",
        "note": "your own sign-in; the session is not metered"
      },
      {
        "what": "Print this sheet",
        "run": "harness commands",
        "note": "the last row prints the raw `git` invocation"
      }
    ]
  }
];
